webtalk_init -webtalk_dir C:/Users/gs10403/CA-LAB-SPR-2026/Vivado Labs/Lab11/Task2/Task2.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 11 13:04:08 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "01a1f592-ff27-459f-b497-013951bc7792" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9ee9ebcdf6e244a6867081315626ec0b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13500" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9036_KB" -context "xsim\\usage"
webtalk_transmit -clientid 80558287 -regid "" -xml C:/Users/gs10403/CA-LAB-SPR-2026/Vivado Labs/Lab11/Task2/Task2.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gs10403/CA-LAB-SPR-2026/Vivado Labs/Lab11/Task2/Task2.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gs10403/CA-LAB-SPR-2026/Vivado Labs/Lab11/Task2/Task2.sim/sim_1/behav/xsim/xsim.dir/tb_processor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
