webtalk_init -webtalk_dir C:/Users/gs10403/Downloads/CA-LAB-SPR-2026-main/CA-LAB-SPR-2026-main/Vivado Labs/Lab11/Task1/Task1.sim/sim_1/behav/xsim/xsim.dir/tb_pc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 16 16:45:57 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "be390297-aeae-4b42-b65a-a6765e92df21" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a5076055fa414e098235b140e4d9f067" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-13500T" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1613 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "90 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8480_KB" -context "xsim\\usage"
webtalk_transmit -clientid 175893822 -regid "" -xml C:/Users/gs10403/Downloads/CA-LAB-SPR-2026-main/CA-LAB-SPR-2026-main/Vivado Labs/Lab11/Task1/Task1.sim/sim_1/behav/xsim/xsim.dir/tb_pc_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/gs10403/Downloads/CA-LAB-SPR-2026-main/CA-LAB-SPR-2026-main/Vivado Labs/Lab11/Task1/Task1.sim/sim_1/behav/xsim/xsim.dir/tb_pc_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/gs10403/Downloads/CA-LAB-SPR-2026-main/CA-LAB-SPR-2026-main/Vivado Labs/Lab11/Task1/Task1.sim/sim_1/behav/xsim/xsim.dir/tb_pc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
